### ISSUE TITLE
Confused about text layout

### ISSUE THREAD

**Issue by arzg** [alacritty/crossfont#23]
How should I lay out a line of arbitrary text using crossfont? I’m a bit confused about how best to combine `width` and `left`. Is this algorithm roughly correct?

```rust
let mut x = 0;

for character in text_to_render.chars() {
    let glyph = rasterizer
        .get_glyph(GlyphKey {
            character,
            font_key,
            size,
        })
        .unwrap();

    draw_bitmap_at_pos(glyph, (x, -glyph.top));

    x += glyph.width + glyph.left;
}
```

Should the actual position of each glyph on the screen be `x + glyph.left` instead of just `x` as I have it here?

The algorithm above doesn’t work with any of the monospace fonts I’ve tried; rather than all characters being the same width, characters that would usually have extra space around them just don’t have that space, making them a narrower width than all the other characters.

Note how the six `.`s take up less space than the six `m`s, when they should be the same width:

<img alt="Screen Shot 2021-03-14 at 12 31 38 pm" src="https://user-images.githubusercontent.com/31783266/111054507-4d938480-84c1-11eb-8014-8bb0dcab09a1.png">

In case it matters, I’m running on macOS 11.2.2.

**Comment by chrisduerr** [comment]
This should not differ from the documentation the font systems themselves have (like freetype). The distance you need to move from one character to the next one is called `advance`. So you just need to read the `average_advance` field from the metrics and that's your cell width for monospace fonts.

**Comment by arzg** [comment]
Cool, thanks for the info! Would you be open to a PR that adds an `advance` field to `RasterizedGlyph`? With this PR I would be able to do font layout with proportional fonts, too.

**Comment by chrisduerr** [comment]
PRs to add proper proportional font handling are certainly welcome, but it might be more effort than just adding a single field to the rasterized glyph.
