### ISSUE TITLE
use_thin_strokes has no effect on macOS 12

### ISSUE THREAD

**Issue by cattyhouse** [alacritty/crossfont#36]
This is the changes that make it work
https://github.com/alacritty/alacritty/issues/4616#issuecomment-860810609

without this change, **use_thin_strokes** does nothing on macOS 12

can you merge this? 

```diff
ben@BeniMac2020 crossfont % git diff
diff --git a/src/darwin/mod.rs b/src/darwin/mod.rs
index aded7a7..9a0f84f 100644
--- a/src/darwin/mod.rs
+++ b/src/darwin/mod.rs
@@ -445,10 +445,13 @@ impl Font {
 
         if use_thin_strokes {
             cg_context.set_font_smoothing_style(16);
+            cg_context.set_allows_font_smoothing(false);
+            cg_context.set_should_smooth_fonts(false);
+        } else {
+            cg_context.set_allows_font_smoothing(true);
+            cg_context.set_should_smooth_fonts(true);
         }
 
-        cg_context.set_allows_font_smoothing(true);
-        cg_context.set_should_smooth_fonts(true);
         cg_context.set_allows_font_subpixel_quantization(true);
         cg_context.set_should_subpixel_quantize_fonts(true);
         cg_context.set_allows_font_subpixel_positioning(true);
```

**Comment by chrisduerr** [comment]
> cg_context.set_font_smoothing_style(16);
> cg_context.set_allows_font_smoothing(false);
> cg_context.set_should_smooth_fonts(false);

It seems to me like these three lines would be in conflict with each other? When you disable font smoothing, surely setting the font smoothing style doesn't make any sense?

**Comment by cattyhouse** [comment]
> > cg_context.set_font_smoothing_style(16);
> > cg_context.set_allows_font_smoothing(false);
> > cg_context.set_should_smooth_fonts(false);
> 
> It seems to me like these three lines would be in conflict with each other? When you disable font smoothing, surely setting the font smoothing style doesn't make any sense?

then `cg_context.set_font_smoothing_style(16);` should be moved to 
```
else {
}
```

**Comment by chrisduerr** [comment]
> then cg_context.set_font_smoothing_style(16); should be moved to

You want to move logic that previously **only** applied to one conditional block to the opposite block? That doesn't make much sense, does it?

**Comment by cattyhouse** [comment]
> > then cg_context.set_font_smoothing_style(16); should be moved to
> 
> You want to move logic that previously **only** applied to one conditional block to the opposite block? That doesn't make much sense, does it?

well, i am not the one that made the patch, but i tested it, it works on macOS 12, all characters are thin stroke, with `use_thin_strokes: true`. i don't quite know how the code works actually :)

**Comment by chrisduerr** [comment]
> i don't quite know how the code works actually

Well, if nobody knows how the code works, then it certainly will not be merged.

If I'm going to send any PR to change the thin strokes behavior on macOS, it will be to remove it completely. I'm personally not interested in this feature and think it's not very beneficial to have anymore.

So if someone else actually cares about thin strokes, they should put in the effort to figure these things out and ensure they work on all macOS systems. Just sending in some patch that might work some of the time won't cut it.

**Comment by chrisnc** [comment]
@chrisduerr I've been experimenting with this a bit and have a patch of crossfont and alacritty that decides what to do based on the AppleFontSmoothing user default, which is what the system uses now to decide this behavior, rather than making this a preference in alacritty/crossfont. Is this something you would be interested in? If so I can polish it up and push it for review, but don't want to waste your time if that's not an approach you'd prefer.

**Comment by kchibisov** [comment]
Can you configure this default actually? Patches are always welcome, especially for macOS, given that it's not what core contributors use.

I'll be the one reviewing patch anyway, so go ahead.

**Comment by chrisnc** [comment]
@kchibisov Sure, I will open a PR and we can discuss further there.
