### ISSUE TITLE
switch from `servo-fontconfig` to `fontconfig`

### ISSUE THREAD

**Issue by xMAC94x** [alacritty/crossfont#53]
`servo-fontconfig` had its latest release over 2 years ago. It's no longer needed by servo itself and prob wont receive any updates soon. It depends on old crates like `freetype-sys 0.13` .
I think we should phase `servo-fontconfig` out in favor for other crates.
This would also solve #44

**Comment by chrisduerr** [comment]
The two crates serve different purposes and I have no interest working with a crate where I can't just use the C functions 1:1.

If you're interested in trying to migrate the crate feel free to test things out and send a PR, but I don't plan to do it myself.
