### ISSUE TITLE
Turned off font smoothing is not detected correctly on macOS

### ISSUE THREAD

**Issue by erikolofsson** [alacritty/crossfont#62]
I was trying to figure out why my font rendering looked incorrect in Alacritty and I finally traced it to the way i set the font smoothing:
```
defaults -currentHost write -g AppleFontSmoothing 0
```
I have been doing this for years, and it seems apple allows a string as well as an integer for this. 

While I have fixed my problem by storing the value as an integer it might be useful to fix the detection to work the same as in macOS?

Tested fix:
https://github.com/erikolofsson/crossfont/commit/2844bc8e4afe0fe9c8159c8fe511a39d9c77437a

**Comment by kchibisov** [comment]
Probably should send a patch then?
