### ISSUE TITLE
Panic while redering space in NotoSans-Regular

### ISSUE THREAD

**Issue by Diegovsky** [alacritty/crossfont#64]
I've been thorugh a a bit of a rabbit hole today because of a segfault in `freetype-rs`. After reading logs and stack traces, it is caused by this crate using a way too low version of `freetype-rs`. From what I have gathered, the issue happens with some characters that are blanks. 

This is because `Face::load_glyph` can populate the slot with valid information, but no bitmap buffer, leaving it empty. However, in C, an empty slice is represented as (null, 0) but this is invalid in rust, causing a panic when trying to load it in `crossfont`. Here's the offending code: [link](https://docs.rs/freetype-rs/0.26.0/src/freetype/bitmap.rs.html#65-72).

This issue was fixed in [this](https://github.com/PistonDevelopers/freetype-rs/commit/069ada9e5c7f00421df51152c2d798a592eeb2da) commit, and [later released as version 30.1](https://github.com/PistonDevelopers/freetype-rs/commits/master/?since=2022-04-28&until=2022-04-28).

Related issue: #44

**Comment by kchibisov** [comment]
See https://github.com/alacritty/crossfont/pull/65

I think we kind of can propagate this bump, given that only sctk-adwaita and alacritty depend on crossfont according to crates.io, thus it's likely not that big of a deal, given that we won't break binary crates, I think.

**Comment by Diegovsky** [comment]
Btw, thank you for being bery quick to respond!

**Comment by chrisduerr** [comment]
> If you could, make this a patch number bump. That way, it get's automatically selected by the resolver

It's a breaking change, so we can't do that.

**Comment by Diegovsky** [comment]
Understandable. Thank you very much again :)
